apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  username: {{ .Values.usernameDB | quote }}
  {{- if eq .Values.usernameDB "superAdminDB" }}
  mug: true
  {{- end }}